### ISSUE TITLE
Playbook bootstrapping-playbook.yml failed on TASK [ntp : Copy the ntp.conf template file]

### ISSUE THREAD

**Issue by jackiehjm** [Wind-River/meta-akraino#37]
Error:

```
TASK [ntp : Copy the ntp.conf template file] ***********************************
Saturday 08 February 2020  07:33:18 +0000 (0:00:00.013)       0:00:03.613 *****
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 2] No such file or directory
fatal: [controller-1]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

NO MORE HOSTS LEFT *************************************************************

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
controller-1               : ok=6    changed=4    unreachable=0    failed=1

Saturday 08 February 2020  07:33:44 +0000 (0:00:26.303)       0:00:29.917 *****
===============================================================================
ntp : Copy the ntp.conf template file ---------------------------------- 26.30s
Report installation progress -------------------------------------------- 2.70s
initial_poweroff_hosts : Ensure all the nodes in the deployment are powered-off. --- 0.32s
Report installation progress -------------------------------------------- 0.29s
ntp : command ----------------------------------------------------------- 0.15s
initial_poweroff_hosts : set_fact --------------------------------------- 0.05s
ntp : Add the OS specific variables ------------------------------------- 0.03s
ntp : Install the required packages in Debian derivatives --------------- 0.01s
[2020-02-08 07:33:44,587   ERROR cmactivateserverhandler(100)] Skipping installationactivator, got exception Playbook bootstrapping-playbook.yml failed

```

**Comment by jackiehjm** [comment]
output with -vvv
```
TASK [ntp : Copy the ntp.conf template file] ***********************************
task path: /etc/ansible/roles/ntp/tasks/main.yml:13
Saturday 08 February 2020  07:18:58 +0000 (0:00:00.013)       0:00:05.775 *****
container_name: "controller-1"
physical_host: "controller-1"
container_name: "controller-1"
physical_host: "controller-1"
<172.20.1.26> ESTABLISH SSH CONNECTION FOR USER: newadmin
<172.20.1.26> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=newadmin -o ConnectTimeout=5 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=64 -o ServerAliveCountMax=1024 -o Compression=no -o TCPKeepAlive=yes -o VerifyHostKeyDNS=no -o ForwardX11=no -o ForwardAgent=yes -T -o ControlPath=/home/newadmin/.ansible/cp/%h 172.20.1.26 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<172.20.1.26> (0, '/home/newadmin\n', '')
container_name: "controller-1"
physical_host: "controller-1"
<172.20.1.26> ESTABLISH SSH CONNECTION FOR USER: newadmin
<172.20.1.26> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=newadmin -o ConnectTimeout=5 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=64 -o ServerAliveCountMax=1024 -o Compression=no -o TCPKeepAlive=yes -o VerifyHostKeyDNS=no -o ForwardX11=no -o ForwardAgent=yes -T -o ControlPath=/home/newadmin/.ansible/cp/%h 172.20.1.26 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/newadmin/.ansible/tmp/ansible-tmp-1581146338.76-169020961752235 `" && echo ansible-tmp-1581146338.76-169020961752235="` echo /home/newadmin/.ansible/tmp/ansible-tmp-1581146338.76-169020961752235 `" ) && sleep 0'"'"''
<172.20.1.26> (0, 'ansible-tmp-1581146338.76-169020961752235=/home/newadmin/.ansible/tmp/ansible-tmp-1581146338.76-169020961752235\n', '')
Using module file /usr/lib/python2.7/site-packages/ansible/modules/files/stat.py
container_name: "controller-1"
physical_host: "controller-1"
<172.20.1.26> ESTABLISH SSH CONNECTION FOR USER: newadmin
<172.20.1.26> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=newadmin -o ConnectTimeout=5 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=64 -o ServerAliveCountMax=1024 -o Compression=no -o TCPKeepAlive=yes -o VerifyHostKeyDNS=no -o ForwardX11=no -o ForwardAgent=yes -T -o ControlPath=/home/newadmin/.ansible/cp/%h 172.20.1.26 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-fdfexgzewyxhxzfmtbzonqgugixkxmbv; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<172.20.1.26> (0, '\n{"invocation": {"module_args": {"checksum_algorithm": "sha1", "get_checksum": true, "path": "/etc/ntp.conf", "checksum_algo": "sha1", "follow": false, "get_md5": false, "get_mime": true, "get_attributes": true}}, "stat": {"charset": "us-ascii", "uid": 0, "exists": true, "attr_flags": "e", "woth": false, "isreg": true, "device_type": 0, "mtime": 1580905371.0, "block_size": 4096, "inode": 3016812, "isgid": false, "size": 644, "executable": false, "isuid": false, "readable": true, "version": "2736266223", "pw_name": "root", "gid": 0, "ischr": false, "wusr": true, "writeable": true, "mimetype": "text/plain", "blocks": 8, "xoth": false, "islnk": false, "nlink": 1, "issock": false, "rgrp": true, "gr_name": "root", "path": "/etc/ntp.conf", "xusr": false, "atime": 1581133223.4887936, "isdir": false, "ctime": 1581129245.0479984, "isblk": false, "wgrp": false, "checksum": "6d653fed9387a7f7d4631e240da7d35f930a6efb", "dev": 2051, "roth": true, "isfifo": false, "mode": "0644", "xgrp": false, "rusr": true, "attributes": ["extents"]}, "changed": false}\n', '')
container_name: "controller-1"
physical_host: "controller-1"
<172.20.1.26> PUT /tmp/tmpEuhNLO/ntp.conf.j2 TO /home/newadmin/.ansible/tmp/ansible-tmp-1581146338.76-169020961752235/source
<172.20.1.26> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=newadmin -o ConnectTimeout=5 -o ControlPath=/home/newadmin/.ansible/cp/%h '[172.20.1.26]'
<172.20.1.26> ssh_retry: attempt: 0, caught exception([Errno 2] No such file or directory) from cmd (/tmp/tmpEuhNLO/ntp.conf.j2...), pausing for 0 seconds
<172.20.1.26> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=newadmin -o ConnectTimeout=5 -o ControlPath=/home/newadmin/.ansible/cp/%h '[172.20.1.26]'
<172.20.1.26> ssh_retry: attempt: 1, caught exception([Errno 2] No such file or directory) from cmd (/tmp/tmpEuhNLO/ntp.conf.j2...), pausing for 1 seconds
<172.20.1.26> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=newadmin -o ConnectTimeout=5 -o ControlPath=/home/newadmin/.ansible/cp/%h '[172.20.1.26]'
<172.20.1.26> ssh_retry: attempt: 2, caught exception([Errno 2] No such file or directory) from cmd (/tmp/tmpEuhNLO/ntp.conf.j2...), pausing for 3 seconds
<172.20.1.26> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=newadmin -o ConnectTimeout=5 -o ControlPath=/home/newadmin/.ansible/cp/%h '[172.20.1.26]'
<172.20.1.26> ssh_retry: attempt: 3, caught exception([Errno 2] No such file or directory) from cmd (/tmp/tmpEuhNLO/ntp.conf.j2...), pausing for 7 seconds
<172.20.1.26> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=newadmin -o ConnectTimeout=5 -o ControlPath=/home/newadmin/.ansible/cp/%h '[172.20.1.26]'
<172.20.1.26> ssh_retry: attempt: 4, caught exception([Errno 2] No such file or directory) from cmd (/tmp/tmpEuhNLO/ntp.conf.j2...), pausing for 15 seconds
<172.20.1.26> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=newadmin -o ConnectTimeout=5 -o ControlPath=/home/newadmin/.ansible/cp/%h '[172.20.1.26]'
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 148, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 551, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/template.py", line 179, in run
    result.update(copy_action.run(task_vars=task_vars))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/copy.py", line 516, in run
    module_return = self._copy_file(source_full, source_rel, content, content_tempfile, dest, task_vars, tmp, delete_remote_tmp)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/copy.py", line 273, in _copy_file
    remote_path = self._transfer_file(source_full, tmp_src)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 310, in _transfer_file
    self._connection.put_file(local_path, remote_path)
  File "/etc/ansible/roles/plugins/connection/ssh.py", line 242, in put_file
    return super(Connection, self).put_file(in_path, out_path)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 971, in put_file
    return self._file_transport_command(in_path, out_path, 'put')
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 240, in wrapped
    return_tuple = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 898, in _file_transport_command
    (returncode, stdout, stderr) = self._bare_run(cmd, in_data, checkrc=False)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 611, in _bare_run
    p = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
fatal: [controller-1]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```
