### ISSUE TITLE
clout-init: ('locale', AttributeError("'SysConf' object has no attribute '_a_to_u'",))

### ISSUE THREAD

**Issue by jackiehjm** [Wind-River/meta-akraino#55]
## cloud-init failed with:

```
[root@intel-x86-64 ~]# cloud-init status --long
status: error
time: Mon, 17 Feb 2020 03:00:55 +0000
detail:
('locale', AttributeError("'SysConf' object has no attribute '_a_to_u'",))

[root@intel-x86-64 ~]# cat /run/cloud-init/status.json
{
 "v1": {
  "datasource": "DataSourceNone",
  "init": {
   "errors": [],
   "finished": 1581908454.142498,
   "start": 1581908327.08291
  },
  "init-local": {
   "errors": [],
   "finished": null,
   "start": null
  },
  "modules-config": {
   "errors": [
    "('locale', AttributeError(\"'SysConf' object has no attribute '_a_to_u'\",))"
   ],
   "finished": 1581908454.751672,
   "start": 1581908454.619691
  },
  "modules-final": {
   "errors": [],
   "finished": 1581908455.33227,
   "start": 1581908455.217011
  },
  "modules-init": {
   "errors": [],
   "finished": null,
   "start": null
  },
  "stage": null
 }
}

```

**Comment by jackiehjm** [comment]
The default locale is en_US.UTF-8 in build185

**Comment by jackiehjm** [comment]
## More logs in /var/log/cloud-init.log
```
2020-02-17 03:00:54,734 - stages.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_locale.pyc'>) with frequency once-per-instance
2020-02-17 03:00:54,734 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2020-02-17 03:00:54,734 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_locale - wb: [644] 20 bytes
2020-02-17 03:00:54,735 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_locale'>)
2020-02-17 03:00:54,735 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2020-02-17 03:00:54,735 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2020-02-17 03:00:54,735 - handlers.py[DEBUG]: finish: modules-config/config-locale: FAIL: running config-locale with frequency once-per-instance
2020-02-17 03:00:54,735 - util.py[WARNING]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_locale.pyc'>) failed
2020-02-17 03:00:54,735 - util.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_locale.pyc'>) failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/stages.py", line 793, in _run_modules
    freq=freq)
  File "/usr/lib/python2.7/site-packages/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python2.7/site-packages/cloudinit/helpers.py", line 187, in run
    results = functor(*args)
  File "/usr/lib/python2.7/site-packages/cloudinit/config/cc_locale.py", line 45, in handle
    cloud.distro.apply_locale(locale, locale_cfgfile)
  File "/usr/lib/python2.7/site-packages/cloudinit/distros/rhel.py", line 117, in apply_locale
    rhel_util.update_sysconfig_file(out_fn, locale_cfg)
  File "/usr/lib/python2.7/site-packages/cloudinit/distros/rhel_util.py", line 36, in update_sysconfig_file
    str(contents),
  File "/usr/lib/python2.7/site-packages/cloudinit/distros/parsers/sys_conf.py", line 52, in __str__
    contents = self.write()
  File "/usr/lib/python2.7/site-packages/configobj/__init__.py", line 2046, in write
    comment))
  File "/usr/lib/python2.7/site-packages/cloudinit/distros/parsers/sys_conf.py", line 99, in _write_line
    self._a_to_u('='),
AttributeError: 'SysConf' object has no attribute '_a_to_u'
```
